### ISSUE TITLE
No support for Plog render type

### ISSUE THREAD

**Issue by oriolarcas** [viva64/plog-converter#2]
The `-t plog` render type is supported [in the Windows version](https://github.com/viva64/PlogConverter-MSBuild-VS/blob/master/Pvs.PlogConverter/CmdConverterOptions.cs#L75), but not in the Unix version.

**Comment by PaulEremeeff** [comment]
Hi,

indeed, the plog XML format is not supported in the cross-platform Unix plog-converter. The plog format is a Windows-only internal format used by PVS-Studio Visual Studio extension. Under Unix, you can use the cross-platform json output format, that is supported by all of PVS-Studio extensions, both under Unix, and on Windows.
