### ISSUE TITLE
GitLab json format support

### ISSUE THREAD

**Issue by Elkin-Vasily** [viva64/plog-converter#3]
Hello! Nice utility!

It would be nice to have an output format that is supported by the GitLab code quality testing.

Link in the documentation: https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool

**Comment by PaulEremeeff** [comment]
Hello, and thanks for the tip! Will look into this more closely in the short to mid-term, and post an update here if there is any progress on the subject.

**Comment by PaulEremeeff** [comment]
I wanted to mention here that we've supported GitLab code quality report format in PVS-Studio plog converter utils; this will become available in the next PVS-Studio 7.21 release.

**Comment by Elkin-Vasily** [comment]
@PaulEremeeff thanks a lot! I have tested it, it works almost perfect!

There is one problem. I have got self-hosted Gitlab CE with Gitlab Runners. Code quality issues displayed in Merge Request window got wrong paths (they are not actually wrong they are just absolute for the runner, so not clickable from Giltab Web UI).

For example:
There is a issue on some string in `src/file.cpp`

Path from PVS-Studio.log.gitlab.json looks like:
`/home/gitlab-runner/builds/<build id>/0/<group>/<subgroup>/<project>/src/file.cpp`

But should be: `src/file.cpp` to be clickable

Could you please fix it, or should I create another issue for this?

**Comment by MikhailEvt** [comment]
@Elkin-Vasily 

To make file paths correct, use the --sourcetree-root (-r) flag when running the analysis. 
The run analysis command would then look like this:
`- pvs-studio-analyzer analyzer -r "/home/gitlab-runner/builds/<build id>/0/<group>/<subgroup>/<project>/" -o PVS-Studio.log`

After that, when converting, replace sourcetree-root to an empty string. Converter command:
`- plog-converter -t gitlab -r "" -o PVS-Studio.log.gitlab.json PVS-Studio.log`

**Comment by Elkin-Vasily** [comment]
@MikhailEvt 

Hi! Thanks for reply.

If I do so I've got a result like:
`|?|/src/file.cpp`

**Comment by Evtihevich** [comment]
@Elkin-Vasily 
We will fix this behavior. 
A partial workaround is to use the -r flag with ".". Converter command: 
`- plog-converter -t gitlab -r "." -o PVS-Studio.log.gitlab.json PVS-Studio.log`

**Comment by Elkin-Vasily** [comment]
> @Elkin-Vasily
> We will fix this behavior.
> A partial workaround is to use the -r flag with ".". Converter command:
> `- plog-converter -t gitlab -r "." -o PVS-Studio.log.gitlab.json PVS-Studio.log`

It works! Thanks
