### ISSUE TITLE
Incorrect SARIF file if there is no issues in the code

### ISSUE THREAD

**Issue by akopachov** [viva64/plog-converter#4]
When running PVS-Studio on the code which have all the issues resolved `plog-converter` app produces SARIF file like this:
```json
{
  "version": "2.1.0",
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "PVS-Studio",
          "semanticVersion": "7.21.64848.262",
          "informationUri": "https://pvs-studio.com",
          "rules": null
        }
      },
      "results": null
    }
  ]
}
```
According to JSON Schema `results` and `rules` properties can not be `null`. Instead they should be an empty array `[]`
[Here is](https://github.com/akopachov/flipper-zero_authenticator/actions/runs/3392299510/jobs/5638341814) example of a GitHub pipeline where this issue was found.

As a temp workaround I added following two lines after running `plog-converter`:
```bash
sed -i 's/"results": null/"results": []/g' pvs-report.sarif
sed -i 's/"rules": null/"rules": []/g' pvs-report.sarif
```
It helps, but looks dirty

**Comment by DarkWanderer** [comment]
Same issue for me, raised #6 to fix

**Comment by DarkWanderer** [comment]
@vivaat @SviatoslavRazmyslov are there plans to release a version with fix? The PR is already in `master`

**Comment by vivaat** [comment]
Hey, @DarkWanderer! Thank you once again for the PR. The next release is scheduled at December.
